In [66]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score,confusion_matrix,mean_squared_error,mean_absolute_error
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.model_selection import KFold,StratifiedKFold,LeaveOneOut,ShuffleSplit
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [45]:
df=pd.read_csv("D:\\shru\\Sem 5\\ML\\files\\iris.csv")

In [46]:
df.dtypes

Sepal length    float64
Sepal width     float64
Petal length    float64
Petal width     float64
Class            object
dtype: object

In [47]:
#split the dataset into training and testing sets
features=df[['Sepal length','Sepal width','Petal length','Petal width']].values
classes=df['Class'].values

In [48]:
cv=KFold(n_splits=5,random_state=1,shuffle=True)

In [49]:
#Training
dectree=DecisionTreeClassifier()
scores=cross_val_score(dectree,features,classes,scoring='accuracy',cv=cv)
print("Accuracy: %.2f%%" % (scores.mean()*100.0))

Accuracy: 94.00%


In [50]:
scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.86666667])

In [51]:
skfold=StratifiedKFold(n_splits=5)

In [52]:
#training
dectree=DecisionTreeClassifier()
scores=cross_val_score(dectree,features,classes,scoring="accuracy",cv=skfold)
print("Accuracy: %.2f%%" % (scores.mean()*100.0))

Accuracy: 96.00%


In [53]:
scores

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [54]:
loocv = LeaveOneOut()
dectree=DecisionTreeClassifier()
scores = cross_val_score(dectree,features,classes,scoring='accuracy',cv=loocv)
print("Accuracy:{0}".format(scores.mean()*100.0))

Accuracy:94.66666666666667


In [55]:
scores

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
sh=ShuffleSplit(n_splits=10,test_size=0.30,random_state=100)
dectree=DecisionTreeClassifier()
scores = cross_val_score(dectree,features,classes,scoring='accuracy',cv=sh)
print("Accuracy:{0}".format(scores.mean()*100.0))

Accuracy:95.55555555555554


In [57]:
scores

array([0.95555556, 0.95555556, 0.93333333, 0.95555556, 0.97777778,
       0.93333333, 0.93333333, 0.95555556, 0.95555556, 1.        ])

In [58]:
###########Using SVC calssifier
sv = KFold(n_splits=5,random_state=1,shuffle=True)
dectree=SVC()
scores = cross_val_score(dectree,features,classes,scoring='accuracy',cv=sv)
print("Accuracy:{0}".format(scores.mean()*100.0))

Accuracy:94.66666666666667


In [59]:
scores

array([0.96666667, 0.93333333, 0.9       , 0.96666667, 0.96666667])

In [60]:
skfold = StratifiedKFold(n_splits=5)
dectree=SVC()
scores = cross_val_score(dectree,features,classes,scoring='accuracy',cv=skfold)
print("Accuracy:{0}".format(scores.mean()*100.0))

Accuracy:96.66666666666666


In [61]:
scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [62]:
loocv = LeaveOneOut()
dectree=SVC()
scores = cross_val_score(dectree,features,classes,scoring='accuracy',cv=loocv)
print("Accuracy:{0}".format(scores.mean()*100.0))

Accuracy:96.66666666666667


In [63]:
scores

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [64]:
sh = ShuffleSplit(n_splits=10,test_size=0.30,random_state=100)
dectree=SVC()
scores = cross_val_score(dectree,features,classes,scoring='accuracy',cv=sh)
print("Accuracy:{0}".format(scores.mean()*100.0))

Accuracy:95.77777777777777


In [65]:
scores

array([0.97777778, 0.97777778, 0.93333333, 0.97777778, 0.95555556,
       0.97777778, 0.93333333, 0.93333333, 0.91111111, 1.        ])

In [67]:
######################### using KNeighbour classifier###############
sv = KFold(n_splits=5,random_state=1,shuffle=True)
dectree=KNeighborsClassifier()
scores = cross_val_score(dectree,features,classes,scoring='accuracy',cv=sv)
print("Accuracy:{0}".format(scores.mean()*100.0))

Accuracy:95.33333333333334


In [68]:
scores

array([1.        , 0.96666667, 0.9       , 0.93333333, 0.96666667])

In [69]:
skfold = StratifiedKFold(n_splits=5)
dectree=KNeighborsClassifier()
scores = cross_val_score(dectree,features,classes,scoring='accuracy',cv=skfold)
print("Accuracy:{0}".format(scores.mean()*100.0))

Accuracy:97.33333333333334


In [70]:
scores

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [71]:
loocv = LeaveOneOut()
dectree=KNeighborsClassifier()
scores = cross_val_score(dectree,features,classes,scoring='accuracy',cv=loocv)
print("Accuracy:{0}".format(scores.mean()*100.0))

Accuracy:96.66666666666667


In [72]:
scores

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [73]:
sh = ShuffleSplit(n_splits=10,test_size=0.30,random_state=100)
dectree=KNeighborsClassifier()
scores = cross_val_score(dectree,features,classes,scoring='accuracy',cv=sh)
print("Accuracy:{0}".format(scores.mean()*100.0))

Accuracy:97.33333333333333


In [74]:
scores

array([0.97777778, 0.95555556, 0.95555556, 0.97777778, 0.97777778,
       0.97777778, 0.97777778, 0.95555556, 0.97777778, 1.        ])

In [75]:
############ Fitting the model using k-neighbor classifier#########
(train_feat,test_feat,train_classes,test_classes) = train_test_split(features,classes,test_size=0.2,random_state=40)

In [78]:
kn = KNeighborsClassifier(n_neighbors=4)

In [79]:
kn.fit(train_feat,train_classes)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='uniform')

In [80]:
pred = kn.predict(test_feat)

In [81]:
print("Accuracy:",accuracy_score(test_classes,pred)*100)

Accuracy: 100.0
