In [88]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score,confusion_matrix,mean_squared_error,mean_absolute_error
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.model_selection import KFold,StratifiedKFold,LeaveOneOut,ShuffleSplit
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [74]:
df=pd.read_csv("D:\\shru\\Sem 5\\ML\\files\\mushrooms.csv")

In [75]:
df.dtypes

class                       object
cap-shape                   object
cap-surface                 object
cap-color                   object
bruises                     object
odor                        object
gill-attachment             object
gill-spacing                object
gill-size                   object
gill-color                  object
stalk-shape                 object
stalk-root                  object
stalk-surface-above-ring    object
stalk-surface-below-ring    object
stalk-color-above-ring      object
stalk-color-below-ring      object
veil-type                   object
veil-color                  object
ring-number                 object
ring-type                   object
spore-print-color           object
population                  object
habitat                     object
dtype: object

In [76]:
for i in df:
    print(i," ",df[i].unique())

class   ['p' 'e']
cap-shape   ['x' 'b' 's' 'f' 'k' 'c']
cap-surface   ['s' 'y' 'f' 'g']
cap-color   ['n' 'y' 'w' 'g' 'e' 'p' 'b' 'u' 'c' 'r']
bruises   ['t' 'f']
odor   ['p' 'a' 'l' 'n' 'f' 'c' 'y' 's' 'm']
gill-attachment   ['f' 'a']
gill-spacing   ['c' 'w']
gill-size   ['n' 'b']
gill-color   ['k' 'n' 'g' 'p' 'w' 'h' 'u' 'e' 'b' 'r' 'y' 'o']
stalk-shape   ['e' 't']
stalk-root   ['e' 'c' 'b' 'r' '?']
stalk-surface-above-ring   ['s' 'f' 'k' 'y']
stalk-surface-below-ring   ['s' 'f' 'y' 'k']
stalk-color-above-ring   ['w' 'g' 'p' 'n' 'b' 'e' 'o' 'c' 'y']
stalk-color-below-ring   ['w' 'p' 'g' 'b' 'n' 'e' 'y' 'o' 'c']
veil-type   ['p']
veil-color   ['w' 'n' 'o' 'y']
ring-number   ['o' 't' 'n']
ring-type   ['p' 'e' 'l' 'f' 'n']
spore-print-color   ['k' 'n' 'u' 'h' 'w' 'r' 'o' 'y' 'b']
population   ['s' 'n' 'a' 'v' 'y' 'c']
habitat   ['u' 'g' 'm' 'd' 'p' 'w' 'l']


In [77]:
df['stalk-root'].mode()

0    b
dtype: object

In [78]:
s={'?':'b'}
df['stalk-root']=df['stalk-root'].replace(s)

In [79]:
df['stalk-root']

0       e
1       c
2       c
3       e
4       e
       ..
8119    b
8120    b
8121    b
8122    b
8123    b
Name: stalk-root, Length: 8124, dtype: object

In [80]:
df['class'].replace(to_replace=['p','e'],value=[1,2],inplace=True)
df['cap-shape'].replace(to_replace=['x','b','s','f','k','c'],value=[1,2,3,4,5,6],inplace=True)
df['cap-surface'].replace(to_replace=['s','y','f','g'],value=[1,2,3,4],inplace=True)
df['cap-color'].replace(to_replace=['n','y','w','g','e','p','b','u','c','r'],value=[1,2,3,4,5,6,7,8,9,10],inplace=True)
df['bruises'].replace(to_replace=['t','f'],value=[1,2],inplace=True)
df['odor'].replace(to_replace=['p','a','l','n','f','c','y','s','m'],value=[1,2,3,4,5,6,7,8,9],inplace=True)
df['gill-attachment'].replace(to_replace=['f','a'],value=[1,2],inplace=True)
df['gill-spacing'].replace(to_replace=['c','w'],value=[1,2],inplace=True)
df['gill-size'].replace(to_replace=['n','b'],value=[1,2],inplace=True)
df['gill-color'].replace(to_replace=['k','n','g','p','w','h','u','e','b','r','y','o'],value=[1,2,3,4,5,6,7,8,9,10,11,12],inplace=True)
df['stalk-shape'].replace(to_replace=['e','t'],value=[1,2],inplace=True)
df['stalk-root'].replace(to_replace=['e','c','b','r'],value=[1,2,3,4],inplace=True)
df['stalk-surface-above-ring'].replace(to_replace=['s','f','k','y'],value=[1,2,3,4],inplace=True)
df['stalk-surface-below-ring'].replace(to_replace=['s','f','k','y'],value=[1,2,3,4],inplace=True)
df['stalk-color-above-ring'].replace(to_replace=['w','g','p','n','b','e','o','c','y'],value=[1,2,3,4,5,6,7,8,9],inplace=True)
df['stalk-color-below-ring'].replace(to_replace=['w','p','g','b','n','e','y','o','c'],value=[1,2,3,4,5,6,7,8,9],inplace=True)
df['veil-type'].replace(to_replace=['p'],value=[1],inplace=True)
df['veil-color'].replace(to_replace=['w','n','o','y'],value=[1,2,3,4],inplace=True)
df['ring-number'].replace(to_replace=['o','t','n'],value=[1,2,3],inplace=True)
df['ring-type'].replace(to_replace=['p','e','l','f','n'],value=[1,2,3,4,5],inplace=True)
df['spore-print-color'].replace(to_replace=['k','n','u','h','w','r','o','y','b'],value=[1,2,3,4,5,6,7,8,9],inplace=True)
df['population'].replace(to_replace=['s','n','a','v','y','c'],value=[1,2,3,4,5,6],inplace=True)
df['habitat'].replace(to_replace=['u','g','m','d','p','w','l'],value=[1,2,3,4,5,6,7],inplace=True)

In [82]:
df

class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          1            1          1        1     1   
1         2          1            1          2        1     2   
2         2          2            1          3        1     3   
3         1          1            2          3        1     1   
4         2          1            1          4        2     4   
...     ...        ...          ...        ...      ...   ...   
8119      2          5            1          1        2     4   
8120      2          1            1          1        2     4   
8121      2          4            1          1        2     4   
8122      1          5            2          1        2     7   
8123      2          1            1          1        2     4   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             1          1           1  ...   
1                   1             1          2           1  ...   
2                   1             1          2           2  ...   
3                   1             1          1           2  ...   
4                   1             2          2           1  ...   
...               ...           ...        ...         ...  ...   
8119                2             1          2          11  ...   
8120                2             1          2          11  ...   
8121                2             1          2           2  ...   
8122                1             1          1           9  ...   
8123                2             1          2          11  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                            1                       1   
1                            1                       1   
2                            1                       1   
3                            1                       1   
4                            1                       1   
...                        ...                     ...   
8119                         1                       7   
8120                         1                       7   
8121                         1                       7   
8122                         3                       1   
8123                         1                       7   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                          1          1           1            1          1   
1                          1          1           1            1          1   
2                          1          1           1            1          1   
3                          1          1           1            1          1   
4                          1          1           1            1          2   
...                      ...        ...         ...          ...        ...   
8119                       8          1           3            1          1   
8120                       8          1           2            1          1   
8121                       8          1           3            1          1   
8122                       1          1           1            1          2   
8123                       8          1           3            1          1   

      spore-print-color  population  habitat  
0                     1           1        1  
1                     2           2        2  
2                     2           2        3  
3                     1           1        1  
4                     2           3        2  
...                 ...         ...      ...  
8119                  9           6        7  
8120                  9           4        7  
8121                  9           6        7  
8122                  5           4        7  
8123                  7           6        7  

[8124 rows x 23 columns]

In [83]:
X = df.drop(['class'], axis =1)
Y = df['class']

In [84]:
#Training
cv = KFold(n_splits=5,random_state=1,shuffle=True)
dectree=DecisionTreeClassifier()
scores=cross_val_score(dectree,X,Y,scoring='accuracy',cv=cv)
print("Accuracy: %.2f%%" % (scores.mean()*100.0))

Accuracy: 100.00%


In [85]:
scores

array([1., 1., 1., 1., 1.])

In [86]:
skfold = StratifiedKFold(n_splits=5)
dectree=DecisionTreeClassifier()
scores = cross_val_score(dectree,X,Y,scoring='accuracy',cv=skfold)
print("Accuracy:{0}".format(scores.mean()*100.0))

Accuracy:91.4305115574081


In [87]:
scores

array([0.84246154, 1.        , 1.        , 1.        , 0.72906404])

In [89]:
###########USING SVC #############
cv = KFold(n_splits=5,random_state=1,shuffle=True)
dectree=SVC()
scores = cross_val_score(dectree,X,Y,scoring='accuracy',cv=cv)
print("Accuracy:{0}".format(scores.mean()*100.0))

Accuracy:99.90153846153845


In [90]:
scores

array([0.99692308, 1.        , 0.99876923, 0.99938462, 1.        ])

In [91]:
skfold = StratifiedKFold(n_splits=5)
dectree=SVC()
scores = cross_val_score(dectree,X,Y,scoring='accuracy',cv=skfold)
print("Accuracy:{0}".format(scores.mean()*100.0))

Accuracy:86.41845395983327


In [92]:
scores

array([0.84246154, 0.99938462, 0.97969231, 1.        , 0.49938424])

In [93]:
##################Using K-neighbor############
cv = KFold(n_splits=5,random_state=1,shuffle=True)
dectree= KNeighborsClassifier()
scores = cross_val_score(dectree,X,Y,scoring='accuracy',cv=cv)
print("Accuracy:{0}".format(scores.mean()*100.0))

Accuracy:99.97538461538461


In [94]:
scores

array([0.99876923, 1.        , 1.        , 1.        , 1.        ])

In [95]:
skfold = StratifiedKFold(n_splits=5)
dectree=KNeighborsClassifier()
scores = cross_val_score(dectree,X,Y,scoring='accuracy',cv=skfold)
print("Accuracy:{0}".format(scores.mean()*100.0))

Accuracy:86.68942781356576


In [96]:
scores

array([0.82584615, 1.        , 0.99261538, 1.        , 0.51600985])

In [97]:
############Fitting using decision tree classifier
(train_feat,test_feat,train_classes,test_classes)=train_test_split(X,Y,train_size=0.8,random_state=1)

In [98]:
#Training
dectree=DecisionTreeClassifier()
dectree.fit(train_feat,train_classes)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [99]:
#Testing
pred=dectree.predict(test_feat)
print("Accuracy:",accuracy_score(test_classes,pred)*100)

Accuracy: 100.0
