In [1]:
#load library
import numpy as np
import pandas as pd

In [2]:
#create a vector as a row
vector_row=np.array([1,2,3])

In [3]:
#create a vector as a column
vector_column=np.array([[1],[2],[3]])

In [4]:
vector_row

array([1, 2, 3])

In [5]:
vector_column

array([[1],
       [2],
       [3]])

In [6]:
#create a matrix
matrix=np.array([[1,2],
                 [1,2],
                 [1,2]])

In [7]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

In [8]:
from scipy import sparse

In [15]:
#create a matrix
matrix=np.array([[0,0],
                [0,1],
                [3,0]])
#create compressed sparse row (CSR) matrix
matrix_sparse=sparse.csr_matrix(matrix)

In [12]:
matrix

array([[0, 0],
       [0, 1],
       [3, 0]])

In [16]:
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.intc'>'
	with 2 stored elements in Compressed Sparse Row format>

In [17]:
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [18]:
#create larger matrix
matrix_large=np.array([[0,0,0,0,0,0,0,0,0,0],
                      [0,1,0,0,0,0,0,0,0,0],
                      [3,0,0,0,0,0,0,0,0,0]])

In [19]:
#create compressed sparse row(CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)


In [20]:
#view larger sparse matrix
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


In [21]:
#create row vector
vector=np.array([1,2,3,4,5,6])

In [22]:
#select third element of vector
vector[2]

3

In [23]:
#create matrix
matrix=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [24]:
#select second row, second column
matrix[1,1]

5

In [25]:
#select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [27]:
#select everything up to and including the third element
vector[:6]

array([1, 2, 3, 4, 5, 6])

In [28]:
#selecct everythin after third element
vector[4:]

array([5, 6])

In [29]:
#select the last element
vector[-1]

6

In [30]:
#select the second last element
vector[-2]

5

In [32]:
#select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
#select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [34]:
#create matrix
matrix=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

In [35]:
#view number of elements (rows * columns)
matrix.size

12

In [36]:
#view number of rows and columns
matrix.shape

(3, 4)

In [37]:
matrix.ndim

2

In [38]:
vector.ndim

1

In [39]:
#create a matrix
matrix=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [40]:
#create function that double the values
doub=lambda i:i*i

In [41]:
#create vectorized function
vec_double=np.vectorize(doub)

In [42]:
#Apply function to all elements in matrix
vec_double(matrix)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [43]:
matrix * matrix

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [44]:
#return maximum element
np.max(matrix)

9

In [45]:
np.min(matrix)

1

In [46]:
#find max element in each column
np.max(matrix,axis=0)

array([7, 8, 9])

In [47]:
#find max element in each row
np.max(matrix,axis=1)

array([3, 6, 9])

In [48]:
#return mean
np.mean(matrix)

5.0

In [49]:
#return variance
np.var(matrix)

6.666666666666667

In [50]:
#return std deviation
np.std(matrix)

2.581988897471611

In [ ]:
#### RESHAPPEEE ARRAAYYY

In [51]:
#create 4 X 3 matrix
matrix=np.array([[1,2,3],
                [4,5,6],
                [7,8,9],
                [10,11,12]])

In [52]:
#reshape matrix into 2X6 matrix
matrix.reshape(2,6)

##cant reshape into 2X7 coz their should be 14 elements but we have only 12 elements

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [53]:
matrix.reshape(1,-1)
##its still two dimentsion array as it has 2 brackets

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [54]:
matrix.reshape(12)
#its 1-dimensional arraya

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [57]:
#flatten matrix
matrix.flatten()

##converts 2-d to 1-d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [55]:
#Transpose matrix
matrix.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [58]:
#transpose vector
np.array([1,2,3,4,5,6]).T

##its 1d array

array([1, 2, 3, 4, 5, 6])

In [60]:
#transpose row vector

np.array([[1,2,3,4,5,6]]).T
##itis 2d array

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [61]:
#return diagonal elements
matrix.diagonal()

array([1, 5, 9])

# RETURN DIAGONAL ONE ABOVE THE MAIN 
matrix.diagonal(offset=1

In [62]:
#create matrix
matrix=np.array([[1,2,3],
                [2,4,6],
                [3,8,9]])
matrix

array([[1, 2, 3],
       [2, 4, 6],
       [3, 8, 9]])

In [65]:
#return diagonal one below the main diagonal
matrix.diagonal(offset=-2)

array([3])

In [66]:
#return  trace
matrix.trace()

14

In [67]:
#create two vectors
vector_a=np.array([1,2,3])
vector_b=np.array([4,5,6])

In [68]:
#calculate dot product
np.dot(vector_a,vector_b)

32

In [69]:
vector_a @ vector_b

32

In [70]:
#creat a matrix
matrix_a=np.array([[1,1,1],
                  [1,1,1],
                  [1,1,2]])

In [71]:
#creat a matrix
matrix_b=np.array([[1,1,2],
                  [1,1,3],
                  [1,3,4]])

In [72]:
np.subtract(matrix_a,matrix_b)

array([[ 0,  0, -1],
       [ 0,  0, -2],
       [ 0, -2, -2]])

In [73]:
#multiply two matrices
np.dot(matrix_a,matrix_b)

array([[ 3,  5,  9],
       [ 3,  5,  9],
       [ 4,  8, 13]])

In [74]:
#element wise multiplication
matrix_a * matrix_b

array([[1, 1, 2],
       [1, 1, 3],
       [1, 3, 8]])

In [75]:
#set seed
np.random.seed(0)

##seed is used so that same random no.s are generated again n again
#generate three random floats integers between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [76]:
#generate three random integers between 1 and 10
np.random.randint(0,11,3)

array([3, 7, 9])

In [77]:
#NAN is used for data handling. NAN means not a number
c=np.array([1,2,np.NAN,3,4])

In [78]:
c

array([ 1.,  2., nan,  3.,  4.])

In [79]:
#checking NAN value
np.isnan(c)

array([False, False,  True, False, False])

In [80]:
#c without a NAN value
c[~np.isnan(c)]

array([1., 2., 3., 4.])

In [81]:
#mean
np.mean(c[~np.isnan(c)])

2.5

In [82]:
3==3

True

In [83]:
np.nan==np.nan

False

In [86]:
#infinity
np.inf==np.inf

True

In [87]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
a=a.astype('float')
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [90]:
a[0][0]=np.nan

In [91]:
a[1][1]=np.inf

In [93]:
a

array([[nan,  2.,  3.],
       [ 4., inf,  6.],
       [ 7.,  8.,  9.]])

In [92]:
np.isinf(a)

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [94]:
np.isnan(a)

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [95]:
flag=np.isinf(a)|np.isnan(a)

In [97]:
flag

array([[ True, False, False],
       [False,  True, False],
       [False, False, False]])

In [ ]:
####DATA CLEANINGG###

In [98]:
a[flag]

array([nan, inf])

In [99]:
a[flag]=0

In [100]:
a

array([[0., 2., 3.],
       [4., 0., 6.],
       [7., 8., 9.]])