In [39]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.metrics import accuracy_score,confusion_matrix,mean_squared_error,mean_absolute_error,classification_report
from sklearn.model_selection import train_test_split

In [40]:
bankdata=pd.read_csv("D:\\shru\\Sem 5\\ML\\files\\BankNote_Authentication.csv")

In [41]:
X=bankdata.drop('class',axis=1)
Y=bankdata['class']

In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.20)

In [43]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [44]:
y_predict=svclassifier.predict(X_test)

In [45]:
print(confusion_matrix(y_test,y_predict))

[[157   3]
 [  1 114]]


In [46]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99       160
           1       0.97      0.99      0.98       115

    accuracy                           0.99       275
   macro avg       0.98      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275



In [47]:
svclassifier.score(X_train,y_train)

0.9890610756608933

In [48]:
from sklearn.svm import SVC
svc = SVC(kernel='rbf')
svc.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [49]:
y_predict=svc.predict(X_test)

In [50]:
print(confusion_matrix(y_test,y_predict))

[[159   1]
 [  0 115]]


In [51]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00       160
           1       0.99      1.00      1.00       115

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275



In [52]:
svc.score(X_train,y_train)

0.9963536918869644

In [53]:
from sklearn.svm import SVC
svc = SVC(kernel='poly',degree=3)
svc.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [54]:
y_predict=svc.predict(X_test)

In [55]:
print(confusion_matrix(y_test,y_predict))

[[149  11]
 [  0 115]]


In [56]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       1.00      0.93      0.96       160
           1       0.91      1.00      0.95       115

    accuracy                           0.96       275
   macro avg       0.96      0.97      0.96       275
weighted avg       0.96      0.96      0.96       275



In [57]:
svc.score(X_train,y_train)

0.9726526891522334